Обновление Feat/mesto
Garri-99/mesto-project pull request #2
Opened 2022-07-30 09:10 UTC by Garri-99

2022-07-30 09:11 UTC, VladimirGareev commented
Looks good)

2022-07-30 09:13 UTC, Garri-99 commented
refactoring with OOP

2022-07-30 12:18 UTC, antonmishchenkov commented on src/components/api.js
> +  _checkResponse(res) {
**Отлично:**

Отлично, что обработка ответа от сервера вынесена в отдельный метод

2022-07-30 12:19 UTC, antonmishchenkov commented on src/components/FormValidator.js
> +    const inputList = Array.from(
**Надо исправить:**

Список полей формы и кнопку сабмита необходимо вынести в конструктор класса в качестве полей, чтобы не искать элементы внутри метода и не передавать их в другие методы. 
Необходимо для того, чтобы доступ к этим статичным элементам формы был во всем классе.

```
this._inputList = ...
this._submitButton = ... 
```

2022-07-30 12:21 UTC, antonmishchenkov commented on src/components/Popup.js
> +    document.removeEventListener("keydown", (evt) => this._handleEscClose(evt));
**Надо исправить:**

Удаление слушателя таким образом не имеет никакого эффекта, так как в колбэке анонимная функция. И устанавливать, и удалять слушатель следует неанонимно. Для этого `this._handleEscClose` необходимо привязать к контексту через `bind` в конструкторе класса.

Тогда установка будет: `document.addEventListener("keydown", this._handleEscClose)`

Удаление - аналогично

2022-07-30 12:24 UTC, antonmishchenkov commented on src/components/UserInfo.js
> +    return this._apiGetUserInfo();
Класс `UserInfo` должен осуществлять только DOM логику информации текущего пользователя. Все взаимодействие с сервером следует выполнять в файле `index.js`.

То есть метод `getUserInfo` должен возвращать объект значений имени и профессии пользователя непосредственно со страницы, а `setUserInfo` устанавливать новые значения в эти поля

2022-07-30 12:27 UTC, antonmishchenkov commented on src/index.js
> +              likeCount.textContent = res.likes.length;
**Надо исправить:**

DOM установку/удаление лайка карточке следует вынести в отдельный публичный метод класса Card и вызывать его здесь и на строке 81 для текущего экземпляра карточки

2022-07-30 12:28 UTC, antonmishchenkov commented on src/index.js
> +      cardsSection.renderItems([res]);
**Надо исправить:**

Для добавления новых карточек следует использовать метод `addItem`

2022-07-30 12:29 UTC, antonmishchenkov commented on src/index.js
> +      profileAvatar.src = formValues["url-avatar"];
Надо исправить:

DOM функционал обновления аватара следует вынести в отдельный публичный метод класса `UserInfo` и вызывать его здесь для экземпляра `user`

2022-07-30 12:30 UTC, antonmishchenkov commented on src/index.js
> +      card.remove();
**Надо исправить:**

DOM функционал удаления карточки следует вынести в отдельный публичный метод класса `Card` и вызывать его здесь для текущего удаляемого экземпляра карточки

2022-07-30 12:30 UTC, antonmishchenkov commented on src/index.js
> +Promise.all([user.getUserInfo(), api.getCards()])
**Отлично:**

Отлично, что используется `Promise.all`

2022-07-30 12:31 UTC, antonmishchenkov commented on src/index.js
>      profileAvatar.src = userData.avatar;
**Надо исправить:**

Для добавления начальной информации о пользователе на страницу следует использовать методы класса `UserInfo`: `setUserInfo` и `setUserAvatar`

2022-07-30 12:35 UTC, antonmishchenkov commented on src/index.js
> +    cardsSection.renderItems(cards);
**Надо исправить:**

Перед добавлением начальных карточек необходимо делать инверсию их массива, чтобы последние добавленные карточки оказывались в начале контейнера после перезагрузки страницы, а не в конце.

2022-07-30 12:36 UTC, antonmishchenkov requested changes
Хорошая работа, так держать! Код аккуратен и читабелен.
Есть ряд замечаний, которые необходимо исправить, чтобы работу можно было принять. Все они отмечены как "Надо исправить".

Также если не удается загрузить картинку (некорректная или пустая ссылка, например https://pinterest.ru), ее блок схлопывается по высоте, в результате чего деформируется макет карточки. Класс `element__pic`.
Необходимо сохранять макет карточки при данном кейсе.

Успехов на второй итерации!

2022-07-30 19:46 UTC, VladimirGareev commented on src/components/FormValidator.js
> +    const inputList = Array.from(
Сделано

2022-07-30 22:54 UTC, Garri-99 commented on src/components/Popup.js
> +    document.removeEventListener("keydown", (evt) => this._handleEscClose(evt));
done

2022-07-30 22:55 UTC, Garri-99 commented on src/components/UserInfo.js
> +    return this._apiGetUserInfo();
done

2022-07-30 23:05 UTC, Garri-99 commented on src/index.js
> +      profileAvatar.src = formValues["url-avatar"];
done

2022-07-30 23:06 UTC, Garri-99 commented on src/index.js
>      profileAvatar.src = userData.avatar;
done

2022-07-30 23:16 UTC, Garri-99 commented on src/index.js
> +    cardsSection.renderItems(cards);
done

2022-07-31 10:51 UTC, VladimirGareev commented on src/index.js
> +              likeCount.textContent = res.likes.length;
completed

2022-07-31 12:10 UTC, VladimirGareev commented on src/index.js
> +      cardsSection.renderItems([res]);
done

2022-07-31 16:09 UTC, VladimirGareev commented on src/index.js
> +      card.remove();
done

2022-08-01 10:45 UTC, antonmishchenkov approved these changes
Отлично, замечания были исправлены, работа принимается.
Успехов в дальнейших проектах!

2022-08-01 11:14 UTC, merged